apiVersion: v1
kind: Secret
metadata:
  name: generarcredencialv3-postgresql
type: Opaque
stringData:
  POSTGRESQL_USER: generarcredenciales
  POSTGRESQL_PASSWORD: REEMPLAZAR_POR_UNA_CLAVE_LARGA
  POSTGRESQL_DATABASE: generar_credenciales_v3
